name: Build Application

on:
    push:

jobs:

    angular-build:
        runs-on: ubuntu-latest
        permissions: 
          contents: read
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            
            - name: Set up node
              uses: actions/setup-node@v2
              with:
                node-version: '22'

            - name : Install + Build
              run: |
                npm install -g @angular/cli
                cd app
                npm install
                ng build
    production-build:
        runs-on: ubuntu-latest
        permissions:
          contents: read
        steps:
            - name: Checkout
              uses: actions/checkout@v6
            
            - name: Set up node
              uses: actions/setup-node@v6
              with:
                node-version: '24'

            - name : Install + Build
              run: |
                npm install -g @angular/cli
                cd app
                npm install
                npm run production
